### ISSUE TITLE
求教学如何配置

### ISSUE THREAD

**Issue by Youl1F** [NiToot/DormitoryManagementSystem#1]
感觉这个项目完成度和美观程度非常高，但是本人小白不太会配，现在只能打开login界面，没有连接数据库，也没办法登录，求教学

**Comment by NiToot** [comment]
既然能够找到这个项目的话，我相信你也能流畅浏览各大技术网站。多看看，基础配置都是那固定的几套打发。看看就能打通，通了个性化配置也便更好上手了。
